name: Lighthouse
on: push
jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v10
        with:
          budgetPath: './.github/workflows/lighthouse-budget.json'
          configPath: './.github/workflows/lighthouserc.yml'
